# Generated by Django 5.1.6 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_type_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Зображення категорії'),
        ),
    ]
