# Generated by Django 5.1.6 on 2025-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_product_composition_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
